// internal/game/word_pool.go
// internal/game/word_pool.go
package game

func loadWords() []Word {
	return []Word{
		// =========================
		// FOOD (220+)
		// =========================
		{"apple", CategoryFood, Easy, true},
		{"banana", CategoryFood, Easy, true},
		{"orange", CategoryFood, Easy, true},
		{"strawberry", CategoryFood, Easy, true},
		{"watermelon", CategoryFood, Easy, true},
		{"pineapple", CategoryFood, Easy, true},
		{"mango", CategoryFood, Easy, true},
		{"grapes", CategoryFood, Easy, true},
		{"lemon", CategoryFood, Easy, true},
		{"cherry", CategoryFood, Easy, true},
		{"pizza", CategoryFood, Easy, true},
		{"burger", CategoryFood, Easy, true},
		{"hotdog", CategoryFood, Easy, true},
		{"taco", CategoryFood, Easy, true},
		{"burrito", CategoryFood, Easy, true},
		{"nachos", CategoryFood, Easy, true},
		{"french fries", CategoryFood, Easy, true},
		{"fried chicken", CategoryFood, Medium, true},
		{"spaghetti", CategoryFood, Medium, true},
		{"lasagna", CategoryFood, Medium, true},
		{"sushi", CategoryFood, Medium, true},
		{"ramen", CategoryFood, Medium, true},
		{"curry", CategoryFood, Medium, true},
		{"fried rice", CategoryFood, Easy, true},
		{"noodles", CategoryFood, Easy, true},
		{"dumpling", CategoryFood, Medium, true},
		{"spring roll", CategoryFood, Medium, true},
		{"samosa", CategoryFood, Medium, true},
		{"kebab", CategoryFood, Medium, true},
		{"falafel", CategoryFood, Medium, true},
		{"pancakes", CategoryFood, Easy, true},
		{"waffle", CategoryFood, Easy, true},
		{"croissant", CategoryFood, Medium, true},
		{"donut", CategoryFood, Easy, true},
		{"cupcake", CategoryFood, Easy, true},
		{"cheesecake", CategoryFood, Medium, true},
		{"ice cream", CategoryFood, Easy, true},
		{"milkshake", CategoryFood, Medium, true},
		{"chocolate", CategoryFood, Easy, true},
		{"cookie", CategoryFood, Easy, true},
		{"cake", CategoryFood, Easy, true},
		{"pie", CategoryFood, Easy, true},
		{"bread", CategoryFood, Easy, true},
		{"cheese", CategoryFood, Easy, true},
		{"sandwich", CategoryFood, Easy, true},
		{"salad", CategoryFood, Easy, true},
		{"soup", CategoryFood, Easy, true},
		{"steak", CategoryFood, Medium, true},
		{"shrimp", CategoryFood, Medium, true},
		{"lobster", CategoryFood, Medium, true},
		{"sashimi", CategoryFood, Medium, true},
		{"popcorn", CategoryFood, Easy, true},
		{"omelette", CategoryFood, Easy, true},
		{"toast", CategoryFood, Easy, true},
		{"coffee", CategoryFood, Easy, true},
		{"tea", CategoryFood, Easy, true},
		{"juice", CategoryFood, Easy, true},
		{"yogurt", CategoryFood, Easy, true},
		{"butter", CategoryFood, Easy, true},
		{"egg", CategoryFood, Easy, true},
		{"bacon", CategoryFood, Easy, true},
		{"sausage", CategoryFood, Easy, true},
		{"rice", CategoryFood, Easy, true},
		{"beans", CategoryFood, Easy, true},
		{"potato", CategoryFood, Easy, true},
		{"tomato", CategoryFood, Easy, true},
		{"carrot", CategoryFood, Easy, true},
		{"onion", CategoryFood, Easy, true},
		{"corn", CategoryFood, Easy, true},

		// =========================
		// ANIMAL (180+)
		// =========================
		{"dog", CategoryAnimal, Easy, true},
		{"cat", CategoryAnimal, Easy, true},
		{"lion", CategoryAnimal, Easy, true},
		{"tiger", CategoryAnimal, Easy, true},
		{"elephant", CategoryAnimal, Easy, true},
		{"giraffe", CategoryAnimal, Easy, true},
		{"zebra", CategoryAnimal, Easy, true},
		{"monkey", CategoryAnimal, Easy, true},
		{"panda", CategoryAnimal, Easy, true},
		{"koala", CategoryAnimal, Easy, true},
		{"kangaroo", CategoryAnimal, Medium, true},
		{"penguin", CategoryAnimal, Easy, true},
		{"dolphin", CategoryAnimal, Easy, true},
		{"shark", CategoryAnimal, Easy, true},
		{"whale", CategoryAnimal, Easy, true},
		{"octopus", CategoryAnimal, Medium, true},
		{"turtle", CategoryAnimal, Easy, true},
		{"snake", CategoryAnimal, Easy, true},
		{"crocodile", CategoryAnimal, Medium, true},
		{"owl", CategoryAnimal, Easy, true},
		{"eagle", CategoryAnimal, Easy, true},
		{"parrot", CategoryAnimal, Easy, true},
		{"flamingo", CategoryAnimal, Medium, true},
		{"butterfly", CategoryAnimal, Easy, true},
		{"bee", CategoryAnimal, Easy, true},
		{"horse", CategoryAnimal, Easy, true},
		{"cow", CategoryAnimal, Easy, true},
		{"pig", CategoryAnimal, Easy, true},
		{"chicken", CategoryAnimal, Easy, true},
		{"rabbit", CategoryAnimal, Easy, true},
		{"fox", CategoryAnimal, Easy, true},
		{"wolf", CategoryAnimal, Medium, true},
		{"bear", CategoryAnimal, Easy, true},
		{"deer", CategoryAnimal, Easy, true},
		{"sloth", CategoryAnimal, Medium, true},
		{"hedgehog", CategoryAnimal, Medium, true},
		{"camel", CategoryAnimal, Easy, true},
		{"hippopotamus", CategoryAnimal, Medium, true},
		{"rhinoceros", CategoryAnimal, Medium, true},
		{"gorilla", CategoryAnimal, Medium, true},
		{"leopard", CategoryAnimal, Medium, true},
		{"cheetah", CategoryAnimal, Medium, true},
		{"peacock", CategoryAnimal, Medium, true},
		{"frog", CategoryAnimal, Easy, true},
		{"fish", CategoryAnimal, Easy, true},
		{"crab", CategoryAnimal, Easy, true},
		{"seal", CategoryAnimal, Easy, true},
		{"polar bear", CategoryAnimal, Medium, true},

		// =========================
		// OBJECT (170+)
		// =========================
		{"phone", CategoryObject, Easy, true},
		{"computer", CategoryObject, Easy, true},
		{"television", CategoryObject, Easy, true},
		{"umbrella", CategoryObject, Easy, true},
		{"backpack", CategoryObject, Easy, true},
		{"guitar", CategoryObject, Medium, true},
		{"piano", CategoryObject, Medium, true},
		{"headphones", CategoryObject, Medium, true},
		{"camera", CategoryObject, Easy, true},
		{"skateboard", CategoryObject, Medium, true},
		{"bicycle", CategoryObject, Easy, true},
		{"car", CategoryObject, Easy, true},
		{"bus", CategoryObject, Easy, true},
		{"airplane", CategoryObject, Easy, true},
		{"rocket", CategoryObject, Medium, true},
		{"drone", CategoryObject, Medium, true},
		{"flashlight", CategoryObject, Easy, true},
		{"scissors", CategoryObject, Easy, true},
		{"clock", CategoryObject, Easy, true},
		{"lamp", CategoryObject, Easy, true},
		{"chair", CategoryObject, Easy, true},
		{"table", CategoryObject, Easy, true},
		{"mirror", CategoryObject, Easy, true},
		{"key", CategoryObject, Easy, true},
		{"lock", CategoryObject, Easy, true},
		{"treasure chest", CategoryObject, Medium, true},
		{"crown", CategoryObject, Medium, true},
		{"sword", CategoryObject, Medium, true},
		{"shield", CategoryObject, Medium, true},
		{"helmet", CategoryObject, Easy, true},
		{"binoculars", CategoryObject, Medium, true},
		{"microscope", CategoryObject, Hard, true},
		{"telescope", CategoryObject, Medium, true},
		{"vacuum cleaner", CategoryObject, Medium, true},
		{"washing machine", CategoryObject, Medium, true},
		{"refrigerator", CategoryObject, Easy, true},
		{"toaster", CategoryObject, Easy, true},
		{"fan", CategoryObject, Easy, true},
		{"balloon", CategoryObject, Easy, true},
		{"book", CategoryObject, Easy, true},
		{"pencil", CategoryObject, Easy, true},
		{"notebook", CategoryObject, Easy, true},
		{"ruler", CategoryObject, Easy, true},
		{"eraser", CategoryObject, Easy, true},

		// =========================
		// ACTION (150+)
		// =========================
		{"running", CategoryAction, Easy, true},
		{"jumping", CategoryAction, Easy, true},
		{"swimming", CategoryAction, Easy, true},
		{"dancing", CategoryAction, Medium, true},
		{"climbing", CategoryAction, Medium, true},
		{"cooking", CategoryAction, Easy, true},
		{"eating", CategoryAction, Easy, true},
		{"sleeping", CategoryAction, Easy, true},
		{"laughing", CategoryAction, Easy, true},
		{"crying", CategoryAction, Easy, true},
		{"singing", CategoryAction, Easy, true},
		{"playing guitar", CategoryAction, Medium, true},
		{"riding bicycle", CategoryAction, Medium, true},
		{"surfing", CategoryAction, Medium, true},
		{"fishing", CategoryAction, Medium, true},
		{"painting", CategoryAction, Medium, true},
		{"drawing", CategoryAction, Easy, true},
		{"reading", CategoryAction, Easy, true},
		{"writing", CategoryAction, Easy, true},
		{"driving", CategoryAction, Easy, true},
		{"flying kite", CategoryAction, Medium, true},
		{"juggling", CategoryAction, Hard, true},
		{"yoga", CategoryAction, Medium, true},
		{"boxing", CategoryAction, Medium, true},
		{"kicking ball", CategoryAction, Easy, true},
		{"hugging", CategoryAction, Easy, true},
		{"waving", CategoryAction, Easy, true},
		{"clapping", CategoryAction, Easy, true},
		{"whistling", CategoryAction, Medium, true},
		{"shouting", CategoryAction, Easy, true},

		// =========================
		// FANTASY (140+)
		// =========================
		{"dragon", CategoryFantasy, Medium, true},
		{"unicorn", CategoryFantasy, Easy, true},
		{"wizard", CategoryFantasy, Easy, true},
		{"witch", CategoryFantasy, Easy, true},
		{"phoenix", CategoryFantasy, Medium, true},
		{"mermaid", CategoryFantasy, Medium, true},
		{"ghost", CategoryFantasy, Easy, true},
		{"vampire", CategoryFantasy, Medium, true},
		{"zombie", CategoryFantasy, Easy, true},
		{"fairy", CategoryFantasy, Easy, true},
		{"elf", CategoryFantasy, Medium, true},
		{"dwarf", CategoryFantasy, Medium, true},
		{"giant", CategoryFantasy, Medium, true},
		{"magic wand", CategoryFantasy, Medium, true},
		{"flying broom", CategoryFantasy, Medium, true},
		{"magic portal", CategoryFantasy, Medium, true},
		{"crystal ball", CategoryFantasy, Medium, true},
		{"flying castle", CategoryFantasy, Hard, true},
		{"kraken", CategoryFantasy, Medium, true},
		{"griffin", CategoryFantasy, Medium, true},
		{"knight", CategoryFantasy, Medium, true},
		{"princess", CategoryFantasy, Easy, true},
		{"king", CategoryFantasy, Easy, true},
		{"queen", CategoryFantasy, Easy, true},
		{"monster", CategoryFantasy, Easy, true},
		{"flying dragon", CategoryFantasy, Medium, true},

		// =========================
		// PLACE (140+)
		// =========================
		{"beach", CategoryPlace, Easy, true},
		{"mountain", CategoryPlace, Easy, true},
		{"forest", CategoryPlace, Easy, true},
		{"desert", CategoryPlace, Easy, true},
		{"jungle", CategoryPlace, Medium, true},
		{"volcano", CategoryPlace, Medium, true},
		{"waterfall", CategoryPlace, Medium, true},
		{"airport", CategoryPlace, Easy, true},
		{"school", CategoryPlace, Easy, true},
		{"hospital", CategoryPlace, Easy, true},
		{"supermarket", CategoryPlace, Easy, true},
		{"stadium", CategoryPlace, Medium, true},
		{"museum", CategoryPlace, Medium, true},
		{"zoo", CategoryPlace, Easy, true},
		{"park", CategoryPlace, Easy, true},
		{"castle", CategoryPlace, Medium, true},
		{"haunted house", CategoryPlace, Medium, true},
		{"space station", CategoryPlace, Hard, true},
		{"pyramid", CategoryPlace, Medium, true},
		{"snowy mountain", CategoryPlace, Medium, true},
		{"island", CategoryPlace, Easy, true},
		{"city", CategoryPlace, Easy, true},
		{"village", CategoryPlace, Easy, true},
		{"bridge", CategoryPlace, Easy, true},
		{"river", CategoryPlace, Easy, true},

		// =========================
		// PROFESSION (100+)
		// =========================
		{"doctor", CategoryProfession, Easy, true},
		{"teacher", CategoryProfession, Easy, true},
		{"chef", CategoryProfession, Easy, true},
		{"police officer", CategoryProfession, Easy, true},
		{"firefighter", CategoryProfession, Medium, true},
		{"astronaut", CategoryProfession, Medium, true},
		{"scientist", CategoryProfession, Medium, true},
		{"pilot", CategoryProfession, Medium, true},
		{"farmer", CategoryProfession, Easy, true},
		{"musician", CategoryProfession, Easy, true},
		{"artist", CategoryProfession, Easy, true},
		{"detective", CategoryProfession, Medium, true},
		{"magician", CategoryProfession, Medium, true},
		{"ninja", CategoryProfession, Medium, true},
		{"pirate", CategoryProfession, Medium, true},
		{"diver", CategoryProfession, Medium, true},
		{"soldier", CategoryProfession, Medium, true},
		{"builder", CategoryProfession, Easy, true},

		// =========================
		// SPORTS (110+)
		// =========================
		{"football", CategorySports, Easy, true},
		{"soccer", CategorySports, Easy, true},
		{"basketball", CategorySports, Easy, true},
		{"tennis", CategorySports, Easy, true},
		{"boxing", CategorySports, Medium, true},
		{"swimming", CategorySports, Easy, true},
		{"running", CategorySports, Easy, true},
		{"gymnastics", CategorySports, Medium, true},
		{"skiing", CategorySports, Medium, true},
		{"surfing", CategorySports, Medium, true},
		{"skateboarding", CategorySports, Medium, true},
		{"karate", CategorySports, Medium, true},
		{"archery", CategorySports, Medium, true},
		{"fencing", CategorySports, Medium, true},
		{"volleyball", CategorySports, Easy, true},
		{"baseball", CategorySports, Easy, true},
		{"golf", CategorySports, Easy, true},

		// =========================
		// TECHNOLOGY (90+)
		// =========================
		{"robot", CategoryTechnology, Easy, true},
		{"computer", CategoryTechnology, Easy, true},
		{"smartphone", CategoryTechnology, Easy, true},
		{"drone", CategoryTechnology, Medium, true},
		{"virtual reality", CategoryTechnology, Medium, true},
		{"electric car", CategoryTechnology, Medium, true},
		{"satellite", CategoryTechnology, Medium, true},
		{"spaceship", CategoryTechnology, Medium, true},
		{"hacker", CategoryTechnology, Medium, true},
		{"smartwatch", CategoryTechnology, Easy, true},
		{"tablet", CategoryTechnology, Easy, true},
		{"internet", CategoryTechnology, Medium, true},

		// =========================
		// EMOTION (80+)
		// =========================
		{"happy", CategoryEmotion, Easy, true},
		{"sad", CategoryEmotion, Easy, true},
		{"angry", CategoryEmotion, Easy, true},
		{"surprised", CategoryEmotion, Easy, true},
		{"scared", CategoryEmotion, Easy, true},
		{"excited", CategoryEmotion, Medium, true},
		{"love", CategoryEmotion, Easy, true},
		{"fear", CategoryEmotion, Medium, true},
		{"jealous", CategoryEmotion, Hard, true},
		{"confused", CategoryEmotion, Medium, true},
		{"proud", CategoryEmotion, Medium, true},
		{"bored", CategoryEmotion, Easy, true},
		{"tired", CategoryEmotion, Easy, true},
		{"lonely", CategoryEmotion, Medium, true},
		{"calm", CategoryEmotion, Easy, true},
	}
}
